{
 "title": "SQL DB  Storage",
 "tags": [ "Azure SQL DB" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "ServerName",
    "query": " select sql_instance from (select  \"sql_instance\", LAST(\"engine_edition\")  from \"sqlserver_server_properties\" where  \"engine_edition\" = 5 and $timeFilter  GROUP BY sql_instance)"
   },
   {
    "name": "DatabaseName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_db_resource_governance\" WITH KEY=\"database_name\"  WHERE $timeFilter  AND sql_instance =~  /$InstanceName/"
   }
  ]
 },
 "panels": [
  { "title": "Azure SQL DB Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SELECT last(\"server_memory\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tier",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW  TAG VALUES WITH KEY = \"sku\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Level Objective",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "total_storage_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Log Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "primary_max_log_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "primary_group_max_workers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Max IO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "primary_group_max_io" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Database IO Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"read_latency_ms\", 1s)/  non_negative_derivative(\"reads\", 1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND   \"database_name\" =~ /^$DatabaseName$/  ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "read_latency_ms" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"write_latency_ms\", 1s) / non_negative_derivative(\"writes\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND (\"database_name\" =~ /^$DatabaseName$/ )) AND $timeFilter GROUP BY \"database_name\",database_id::string, \"logical_filename\"",
       "select": [
        [
         { "params": [ "read_latency_ms" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Reads IO's queued -  Resource Governance Impact",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"rg_read_stall_ms\", 1s)/ non_negative_derivative(\"reads\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "rg_read_stall_ms" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Write IO's queued -  Resource Governance Impact",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"rg_write_stall_ms\", 1s)/ non_negative_derivative(\"reads\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND  \"database_name\" =~ /^$DatabaseName$/ ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "rg_write_stall_ms" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Read Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"read_bytes\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "OR", "key": "database_name", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Write Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"write_bytes\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/  ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Reads/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"reads\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND (\"database_name\" =~ /^$DatabaseName$/ OR \"database_name\" ='tempdb' ) ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "Writes/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | $tag_logical_filename",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" },
        { "params": [ "logical_filename" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": "SELECT non_negative_derivative(\"writes\", 1s) FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND (\"database_name\" =~ /^$DatabaseName$/ OR \"database_name\" ='tempdb' ) ) AND $timeFilter GROUP BY \"database_name\", \"logical_filename\"",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
       ]
      }
     ]
    },
    {
     "title": "RBPEX Vs Data Files Reads ( IOPS)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | DataLogFiles",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": " SELECT  non_negative_derivative(sum(\"reads\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND database_id > 2) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "logical_filename", "operator": "!=", "value": "RBPEX" }
       ]
      },
      {
       "alias": "$tag_database_name | RBPEX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"reads\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND database_id = 0) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "TempDB | DataLogFiles",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"reads\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND  database_id = 2 ) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RBPEX V/s Data Files writes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | All files",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": " SELECT  non_negative_derivative(sum(\"writes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND database_id > 2) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "logical_filename", "operator": "!=", "value": "RBPEX" }
       ]
      },
      {
       "alias": "$tag_database_name | RBPEX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"writes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND database_id = 0) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Tempdb| AllFiles",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"writes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND  database_id = 2 ) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RBPEX Vs Data Files Read Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | AllFiles",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": " SELECT  non_negative_derivative(sum(\"read_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND  \"database_id\" >2) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "logical_filename", "operator": "!=", "value": "RBPEX" }
       ]
      },
      {
       "alias": "$tag_database_name | RBPEX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"read_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND   \"database_id\" = 0) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Tempdb | AllFiles",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"write_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND  \"database_id\" = 2 ) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RBPEX Vs Data Files Write Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_database_name | AllFiles",
       "groupBy": [
        { "params": [ "database_name" ], "type": "tag" }
       ],
       "measurement": "sqlserver_database_io",
       "query": " SELECT  non_negative_derivative(sum(\"write_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND \"database_id\" >2) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
        { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "logical_filename", "operator": "!=", "value": "RBPEX" }
       ]
      },
      {
       "alias": "$tag_database_name | RBPEX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"write_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND \"database_id\" = 0) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Tempdb | AllFiles",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " SELECT  non_negative_derivative(sum(\"write_bytes\"),1s)  FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"database_name\" =~ /^$DatabaseName$/ AND  \"database_id\" = 2 ) AND $timeFilter GROUP BY \"database_name\", TIME(15s)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Database File Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Data File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log File Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Used Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Free space in tempdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Free Space in tempdb (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Free space in tempdb %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"freespace\") / mean(\"tempdbsize\") * 100.0 AS PercenttempdbFree\nFROM \n(SELECT (\"value\") AS \"freespace\" FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" = 'Free Space in tempdb (KB)' AND \"database_name\" =~ /^$DatabaseName$/ AND $timeFilter) )\n,\n(SELECT (\"value\") AS \"tempdbsize\" FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" = 'Data File(s) Size (KB)' AND \"database_name\" =~ /^$DatabaseName$/ AND \"instance\" = 'tempdb' AND $timeFilter) GROUP BY \"instance\")\nGROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}