{
 "title": "SQL DB Performance",
 "description": "Azure SQL Database Performance Dashboard",
 "tags": [ "Azure SQL DB" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "Server Name",
    "query": " select sql_instance from (select  \"sql_instance\", LAST(\"engine_edition\")  from \"sqlserver_server_properties\" where  \"engine_edition\" = 5 and $timeFilter  GROUP BY sql_instance)"
   },
   {
    "name": "DatabaseName",
    "label": "DatabaseName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_server_properties\" WITH KEY=\"database_name\"  WHERE $timeFilter  AND sql_instance =~  /$InstanceName/"
   }
  ]
 },
 "panels": [
  { "title": "Azure SQL DB Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tier",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW  TAG VALUES FROM sqlserver_server_properties WITH KEY = \"sku\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "sku" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Level Objective",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW  TAG VALUES from sqlserver_server_properties WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "total_storage_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Log Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "instance_max_log_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "primary_group_max_workers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Max IOPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pool_max_io" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  { "title": "Azure SQL DB Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SQL DB Resource Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "avg_cpu",
     "measurement": "sqlserver_azurestats",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/ AND \"object\" =~ /SQL Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "avg_cpu_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "avg_data_io_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "avg_data_io_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "log_write_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "avg_log_write_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "avg_memory_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "avg_memory_usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "max_worker_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "max_worker_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "max_session_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "max_session_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "avg_instance_cpu_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "avg_instance_cpu_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    },
    {
     "alias": "avg_instance_memory_percent",
     "measurement": "sqlserver_azurestats",
     "select": [
      [
       { "params": [ "avg_instance_memory_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Batch Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/ AND \"object\" =~ /SQL Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:SQL Statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/   AND \"database_name\" =~ /^$DatabaseName$/ AND \"object\" =~ /General Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:General Statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Level Waits and Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "SQL DB Wait Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_azuredb_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceType.*$/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name'", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL DB Signal Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_azuredb_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceType.*$/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "signal_wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name'", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL DB waiting Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_azuredb_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceType.*$/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "waiting_tasks_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name'", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  { "title": "Log Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Log  Flushed Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Bytes Flushed/sec" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Log Flushes/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  { "title": "CPU and Workload Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Total %CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT sum(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/   AND \"database_name\" =~ /^$DatabaseName$/ AND \"object\" =~ /Resource Pool Stats/ AND  \"counter\" = 'CPU usage %') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "CPU usage %" }
     ]
    }
   ]
  },
  {
   "title": "Workload Group - %CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"counter\" = 'CPU usage %' AND \"object\" =~ /Workload Group Stats/ AND \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "CPU usage %" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Schedulers (Optional capture)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler CPU ms/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "total_cpu_usage_ms" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Scheduler Delay ms/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "total_scheduler_delay_ms" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Runnable Task Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "runnable_tasks_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Context switches/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "context_switches_count" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"object\" =~ /Memory Manager/ AND \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Memory Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "clerk_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager: Page Life Expectancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Page life expectancy" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Buffer Manager/ AND \"sql_instance\" =~ /^$InstanceName$/   AND \"database_name\" =~ /^$DatabaseName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Buffer Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Access Methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Access Methods/ AND \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Latch Waits/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"database_name\" =~ /^$DatabaseName$/ AND \"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~/Latches/ AND \"counter\" =~/sec/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "MSSQL$AEE4C419AFA1:Databases" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" }
     ]
    }
   ]
  }
 ]
}