{
 "title": "SQL DB  Storage",
 "tags": [ "Azure SQL DB" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_azurestats\" WITH KEY=\"sql_instance\" WHERE $timeFilter"
   },
   {
    "name": "DatabaseName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_server_properties\" WITH KEY=\"database_name\"  where sql_instance =~  /$InstanceName/"
   }
  ]
 },
 "panels": [
  { "title": "Azure SQL DB Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SELECT last(\"server_memory\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tier",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW  TAG VALUES WITH KEY = \"sku\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Level Objective",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND \"database_name\" =~ /^$DatabaseName$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "total_storage_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Log Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "instance_max_log_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Max workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "instance_max_worker_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Max IO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_db_resource_governance",
     "query": "SELECT last(\"total_storage_mb\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pool_max_io" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  { "title": "Database IO Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Reads/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Writes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name | $tag_logical_filename",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "logical_filename" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Database File Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Data File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log File Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Used Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" },
      { "condition": "AND", "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" }
     ]
    }
   ]
  }
 ]
}